# TDCommon Antibody-Antigen Affinity Prediction Task

In this notebook we'll build models to predict this TDCommons dataset: [Antibody-Antigen Affinity](https://tdcommons.ai/multi_pred_tasks/antibodyaff)

**Definition:** Antibodies recognize pathogen antigens and destroy them. The activity is measured by their binding affinities. This task is to predict the affinity from the amino acid sequences of both antigen and antibodies.

**Impact:** Compared to small-molecule drugs, antibodies have numerous ideal properties such as minimal adverse effect and also can bind to many "undruggable" targets due to different biochemical mechanisms. Besides, a reliable affinity predictor can help accelerate the antibody development processes by reducing the amount of wet-lab experiments.

**Generalization:** The models are expected to extrapolate to unseen classes of antigen and antibody pairs.

**Product:** Antibody, immunotherapy.

**Pipeline:** Activity.



<img src="https://upload.wikimedia.org/wikipedia/commons/e/e6/Atezolizumab_PD-L1_5X8L.png" alt="Space-filling model of the antigen-binding fragment of atezolizumab (pale blue) in complex with PD-L1 (pink)" width="500"/>

> ##### Space-filling model of the antigen-binding fragment of the monocloncal antibody atezolizumab (pale blue) in complex with PD-L1 (pink).
> This antibody is used as a drug to treat several types of cancer. PD-L1 (pink) serves as a "brake" to slow down T-cells. Atezolizumab (pale blue) binds to this brake and allows T-cells to go after (and destroy) cancer cells. If we can develop other types of antibodies that have even higher binding affinities, then we will have better treatments for cancer. That is the goal of the SabDab dataset challenge.
> 
> *Style made to resemble the Protein Data Bank's "Molecule of the Month" series, illustrated by Dr. David S. Goodsell of the Scripps Research Institute. Created using QuteMol (http://qutemol.sourceforge.net) and GIMP. Optimized with OptiPNG. Public domain license.*

## TODO
Instead of joining the antibody and antigen sequence in a single embedding try to embed both separately and pass them in as two input vectors.

In [1]:
import torch

In [2]:
torch.cuda.is_available()

True

## ESM2 Embedder using HuggingFace

[ESM2 protein language model](https://github.com/facebookresearch/esm) to embed protein sequences into an embedding space. We need the embedding space because the computer doesn't know how to handle amino acid sequences. Instead, the ESM2 embedder converts the amino acid sequences into a vector of 320 numbers that the computer can understand. This embedding vector inherently embeds features about the amino acid sequence and the 3D protein structure.

## Load HuggingFace model

In [3]:
from transformers import AutoTokenizer, EsmModel

In [4]:
model_name = "facebook/esm2_t6_8M_UR50D"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = EsmModel.from_pretrained(model_name)

/home/tbreina/antibody-affinity/.pixi/envs/default/lib/python3.11/site-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(
Some weights of EsmModel were not initialized from the model checkpoint at facebook/esm2_t6_8M_UR50D and are newly initialized: ['esm.pooler.dense.bias', 'esm.pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Put tensor(s) on the desired hardware device. If CUDA (GPU) is available, then use that. If not, then use CPU.

In [5]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)

## Multimers

If the protein consists of multiple chains (multimers), then connect them as one long sequence string by inserting a chain of "G" in between.

In [6]:
chain_A = "MRLIPLHNVDQVAKWSARYIVDRINQFQPTEARPFVLGLPTGGTPLKTYEALIELYKAGEVSFKHVVTFNMDEYVGLPKEHPESYHSFMYKNFFDHVDIQEKNINILNGNTEDHDAECQRYEEKIKSYGKIHLFMGGVGVDGHIAFNEPASSLSSRTRIKTLTEDTLIANSRFFDNDVNKVPKYALTIGVGTLLDAEEVMILVTGYNKAQALQAAVEGSINHLWTVTALQMHRRAIIVCDEPATQELKVKTVKYFTELEASAIRSVK"
chain_B = "HPESYHSFMYKNFFDHVDIQEKRTTDINRT"

linker_sequence = "G" * 25  # Put G linker in between chains (hide it later)

multimer_sequence = chain_A + linker_sequence + chain_B

Tokenize the input sequence string

In [7]:
tokenized_multimer = tokenizer([multimer_sequence], return_tensors="pt", add_special_tokens=False)

Renumber the positions of the second chain so that the model knows that the second chain is not really connected.

In [8]:
with torch.no_grad():
    position_ids = torch.arange(len(multimer_sequence), dtype=torch.long)
    position_ids[len(chain_A) + len(linker_sequence):] += 512

In [9]:
tokenized_multimer['position_ids'] = position_ids.unsqueeze(0)

tokenized_multimer = {key: tensor.to(device) for key, tensor in tokenized_multimer.items()}

In [10]:
with torch.no_grad():
    output = model(**tokenized_multimer)

In [11]:
output.keys()

odict_keys(['last_hidden_state', 'pooler_output'])

The embeddings are the last hidden state of the model.

In [12]:
output["last_hidden_state"].shape

torch.Size([1, 322, 320])

In [13]:
position_ids.shape

torch.Size([322])

## Create embedding function

Preprocess data to get the ESM2 embedding space from the raw sequence strings

In [14]:
import numpy as np
from tqdm import tqdm

In [15]:
import numpy as np
import torch
from scipy.interpolate import interp1d

def resample_embedding(embedding, target_length=1024):
    """Resample the embedding to match the target length."""
    current_length = embedding.shape[0]
    if current_length == target_length:
        return embedding
    
    x = np.linspace(0, 1, current_length)
    f = interp1d(x, embedding, axis=0, kind='linear')
    x_new = np.linspace(0, 1, target_length)
    return f(x_new)

def embed_sequence(sequence_strs: str, is_antibody=False):
    """Embed antibody using ESM2 and resample to a fixed length of 1024.
    
    Args:
        sequence_strs(str): List of the heavy and light chain sequence strings
                            It's really a list that has been converted to string because Pandas can't handle arrays

    Returns:
        Numpy array of resampled embeddings with the shape 
        (n_sequences, 1024, embedding_dim)
    """

    embed_sequences = []
    target_length = 1024  # Fixed resampling length
    
    for sequence_str in sequence_strs:

        if is_antibody:
            sequences = sequence_str.split("'")[1:3]
            
            linker_sequence = "G" * 25  # Put G linker in between chains (hide it later)
            multimer_sequence = sequences[0] + linker_sequence + sequences[1]
            
            tokenized_sequence = tokenizer([multimer_sequence], return_tensors="pt", add_special_tokens=False)
        
            with torch.no_grad():
                position_ids = torch.arange(len(multimer_sequence), dtype=torch.long)
                position_ids[len(sequences[0]) + len(linker_sequence):] += 512

        else:
            # ESM2 model has maximum token length of 1024.
            # If sequence is longer, then take the middle 1024 residues.
            if len(sequence_str) > 1024:
                start_position = (len(sequence_str) - 1024) // 2
                sequence_str = sequence_str[start_position:(start_position + 1024)]
                
            tokenized_sequence = tokenizer([sequence_str], return_tensors="pt", add_special_tokens=False)
        
            with torch.no_grad():
                position_ids = torch.arange(len(tokenized_sequence.input_ids[0]), dtype=torch.long)
    
        tokenized_sequence['position_ids'] = position_ids.unsqueeze(0)
    
        tokenized_sequence = {key: tensor.to(device) for key, tensor in tokenized_sequence.items()}
        with torch.no_grad():
            output = model(**tokenized_sequence)
    
        embedding = output["last_hidden_state"]  # (batch_size, sequence_length, embedding_dim)
        embedding_2d = embedding.squeeze(0).cpu().numpy()  # (sequence_length, embedding_dim)

        # Resample to the fixed length of 1024
        resampled_embedding = resample_embedding(embedding_2d, target_length)
        embed_sequences.append(resampled_embedding)

    # Stack all embeddings into a single numpy array, shape (n_sequences, 1024, embedding_dim)
    return np.array(embed_sequences)

## TD Commons - SAbDab Dataset

The SabDab dataset is described on the [Oxford Protein Informatics Group website](https://opig.stats.ox.ac.uk/webapps/sabdab-sabpred/sabdab).

> SAbDab is a database containing all the antibody structures available in the [PDB](https://www.rcsb.org/), annotated and presented in a consistent fashion.
>
> Each structure is annotated with a number of properties including experimental details, antibody nomenclature (e.g. heavy-light pairings), curated affinity data and sequence annotations. You can use the database to inspect individual structures, create and download datasets for analysis, search the database for structures with similar sequences to your query, monitor the known structural repetoire of antibodies, and much more.
>
> SAbDab was built by the [Oxford Protein Informatics Group (OPIG)](https://opig.stats.ox.ac.uk/webapps/sabdab-sabpred/sabdab) under an [open-innovation agreement](https://www.sabsr3.ox.ac.uk/home).
>
> Our antibody prediction tools (such as modelling software, developability prediction software etc.) can be found at our SAbPred site.
>
> Please note that the data contained within SAbDab is available under a CC-BY 4.0 license.

From the [TDCommons dataset description](https://tdcommons.ai/multi_pred_tasks/antibodyaff):

**Dataset Description:** Antibody-antigen affinity measures the efficacy of the antibody to the antigen. Processed from SAbDab dataset, where we only use protein/peptide antigens for sequence compatbility.

**Task Description:** Regression. Given the amino acid sequence of antibody and antigen, predict their binding affinity.

**Dataset Statistics:** 493 pairs, 431 antibodies and 401 antigens.

> Note:
>
> In the antibody column, each antibody is organized from left to right as heavy chain to light chain. Also, we highly suggest you take the log affinity when making prediction.

**Dataset Split:** Random Split

```
from tdc.multi_pred import AntibodyAff
data = AntibodyAff(name = "Protein_SAbDab")
split = data.get_split()
```

**References:**

[[1](https://academic.oup.com/nar/article/50/D1/D1368/6431822)] Schneider, C., Raybould, M.I.J., Deane, C.M. (2022) SAbDab in the Age of Biotherapeutics: Updates including SAbDab-Nano, the Nanobody Structure Tracker. Nucleic Acids Res. 50(D1):D1368-D1372

[[2](http://nar.oxfordjournals.org/content/42/D1/D1140.abstract)] SAbDab paper: Dunbar, J., Krawczyk, K. et al (2014). Nucleic Acids Res. 42. D1140-D1146

[[3](https://academic.oup.com/nar/advance-article/doi/10.1093/nar/gkz827/5573951)] Thera-SAbDab paper: Raybould, M.I.J., Marks, C. et al (2019). Nucleic Acids Res. gkz827

**Dataset License:** CC BY 3.0.

In [16]:
from tdc.multi_pred import AntibodyAff
data = AntibodyAff(name = "Protein_SAbDab")
split = data.get_split()

Found local copy...
Loading...
Done!

In [17]:
import pandas as pd

In [18]:
df = pd.concat([split["train"], split["test"], split["valid"]])

In [19]:
df.to_csv("antibody_affinities.csv")

In [20]:
split["train"].head(5)   # The training dataset

,Antibody_ID,Antibody,Antigen_ID,Antigen,Y
0,4i2x,['EVKLQQSGPELVKPGASVKISCKASGYSFTSYYIHWVKQRPGQG...,signal-regulatory protein gamma,EEELQMIQPEKLLLVTVGKTATLHCTVTSLLPVGPVLWFRGVGPGR...,1.200000e-06
1,5vyf,['EVQLVESGGGLVQPGGSLRLSCAASGFTFSSYAMSWVRQAPGKG...,chimera of major allergen i polypeptide chain ...,VKMAETCPIFYDVFFAVANGNELLLDLSLTKVAATEPERTAMKKIQ...,1.870000e-10
2,3eob,['EVQLVESGGGLVQPGGSLRLSCAASGYSFTGHWMNWVRQAPGKG...,integrin alpha-l,GNVDLVFLFDGSMSLQPDEFQKILDFMKDVMKKLSNTSYQFAAVQF...,2.200000e-09
3,2r56,['QVSLRESGGGLVQPGRSLRLSCTASGFTFRHHGMTWVRQAPGKG...,beta-lactoglobulin,LIVTQTMKGLDIQKVAGTWYSLAMAASDISLLDAQSAPLRVYVEEL...,1.300000e-09
4,4yhz,['EVQLVETGGGVVQPGRSLRLSCTASGFTFRDYWMSWVRQAPGKG...,h3k4me3 peptide,ARTKQTARKSTG,1.100000e-08

In [21]:
split["test"].head(5)   # The test dataset

,Antibody_ID,Antibody,Antigen_ID,Antigen,Y
0,1tzh,['EVQLVESGGGLVQPGGSLRLSCAASGFDIYDDDIHWVRQAPGKG...,vascular endothelial growth factor a,GQNHHEVVKFMDVYQRSYCHPIETLVDIFQEYPDEIEYIFKPSCVP...,1.800000e-09
1,5xmh,['MQVQLVQSGAEVKKPGSSVKVSCKASGGTFSSYPISWVRQAPGQ...,immunoglobulin gamma-1 heavy chain,GPSVFLFPPKPKDTLMISRTPEVTCVVVDVSHEDPEVKFNWYVDGV...,1.600000e-04
2,2ny3,['EVQLVESGAEVKKPGSSVKVSCKASGDTFIRYSFTWVRQAPGQG...,envelope glycoprotein gp120,EVVLVNVTENFNMWKNDMVEQMHEDIISLWDQSLKPCVKLTPLCVG...,8.150000e-07
3,1nca,['QIQLVQSGPELKKPGETVKISCKASGYTFTNYGMNWVKQAPGKG...,influenza a subtype n9 neuraminidase,IRDFNNLTKGLCTINSWHIYGKDNAVRIGEDSDVLVTREPYVSCDP...,8.300000e-09
4,3idx,['QVQLVESGGGVVQPGRSLRLSCAASGFTFRNYAMHWVRQAPGKG...,hiv-1 hxbc2 gp120 core,EVVLVNVTENFNWCKNDMVEQMHEDICSLWDQSLKPCVKLTPLCVG...,4.040000e-09

In [22]:
split["valid"].head(5)   # The validation dataset

,Antibody_ID,Antibody,Antigen_ID,Antigen,Y
0,4ffz,['QVQLLQPGAELVKPGASMKLSCKASGYTFTNWWMHWVRLRPGRG...,envelope protein e,MASMTLKGMSYVMCTGSFKLEKEVAETQHGTVLVQVKYEGTDAPCK...,4.160000e-07
1,2fx9,['QVQLVQSGAEVKRPGSSVTVSCKASGGSFSTYALSWVRQAPGRG...,fragment of hiv glycoprotein gp41,NWFCITRWLWKKKK,1.700000e-08
2,6ddm,['EIQLQQSGPELVKPGASVKVSCKASGYAFTSQNIYWVKQSHGKS...,mhc class i polypeptide-related sequence a,TVPPMVNVTRSEASEGNITVTCRASSFYPRNIILTWRQDGVSLSHD...,4.200000e-10
3,1n64,['QIQLVQSGPELKKPGETVKISCKASGYTFTDFSMHWVNQAPGKG...,genome polyprotein capsid protein c,PGGGQIVGGVYLLPRR,1.300000e-09
4,4iof,['MKKNIAFLLASMFVFSIATNAYAEISEVQLVESGGGLVQPGGSL...,insulin-degrading enzyme,MHHHHHHAAGIPMNNPAIKRIGNHITKSPEDKREYRGLELANGIKV...,4.000000e-09

## Generate the X and y datasets

In [23]:
X_train_antibody = embed_sequence(split["train"]["Antibody"], is_antibody=True)
X_valid_antibody = embed_sequence(split["valid"]["Antibody"], is_antibody=True)
X_test_antibody  = embed_sequence(split["test"]["Antibody"], is_antibody=True)

In [24]:
X_train_antibody.shape

(345, 1024, 320)

In [25]:
X_test_antibody.shape

(99, 1024, 320)

In [26]:
X_train_antigen = embed_sequence(split["train"]["Antigen"])
X_valid_antigen = embed_sequence(split["valid"]["Antigen"])
X_test_antigen  = embed_sequence(split["test"]["Antigen"])

In [27]:
# Recommend to take the log transform on the affinity values to make them more linear
y_train = np.log(split["train"]["Y"].values)
y_valid = np.log(split["valid"]["Y"].values)
y_test =  np.log(split["test"]["Y"].values)

In [28]:
X_train_antibody.shape

(345, 1024, 320)

In [29]:
X_train_antigen.shape

(345, 1024, 320)

In [30]:
X_test_antibody.shape

(99, 1024, 320)

In [31]:
X_test_antigen.shape

(99, 1024, 320)

In [32]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import pytorch_lightning as pl
from torch.utils.data import DataLoader, TensorDataset
from torchmetrics import MeanSquaredError
import matplotlib.pyplot as plt

In [33]:
def create_dataset(antigen, antibody, labels):
    # Convert to tensors and unsqueeze to add a channel dimension
    antigen = torch.Tensor(antigen).unsqueeze(1)  # Adds a channel dimension, shape: [batch_size, 1, sequence_length, embedding_dim]
    antibody = torch.Tensor(antibody).unsqueeze(1)  # Adds a channel dimension, shape: [batch_size, 1, sequence_length, embedding_dim]
    labels = torch.Tensor(labels)

    # Create a dataset where antigen and antibody are treated as separate inputs
    dataset = TensorDataset(antigen, antibody, labels)
    return dataset

# Example usage
train_dataset = create_dataset(X_train_antigen, X_train_antibody, y_train)
val_dataset = create_dataset(X_valid_antigen, X_valid_antibody, y_valid)
test_dataset = create_dataset(X_test_antigen, X_test_antibody, y_test)

train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=32, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

In [34]:
# Example usage
for batch in train_loader:
    antigen_input, antibody_input, labels = batch
    print(f'Antigen Inputs shape: {antigen_input.shape}') 
    print(f'Antibody Inputs shape: {antibody_input.shape}')  
    print(f'Labels shape: {labels.shape}')  # This should give you something like [batch_size]
    break  # Break after first batch to inspect the shape

Antigen Inputs shape: torch.Size([32, 1, 1024, 320])
Antibody Inputs shape: torch.Size([32, 1, 1024, 320])
Labels shape: torch.Size([32])

## Create model to predict affinity

Create a convolutional neural network model that takes the antigen and antibody 2D embeddings as the input and predicts the affinity. The antigen and antibody embeddings are resampled so that they are always a length of 1024 regardless of the original input sequence.

In [35]:
class AffinityPredictor(nn.Module):
    def __init__(self, embedding_dim, sequence_length):
        super(AffinityPredictor, self).__init__()
        
        # Define the 2D convolutional layers for antigen and antibody
        self.conv1 = nn.Conv2d(in_channels=1, out_channels=16, kernel_size=3, stride=1, padding=1)
        self.bn1 = nn.BatchNorm2d(16)
        self.conv2 = nn.Conv2d(in_channels=16, out_channels=32, kernel_size=3, stride=1, padding=1)
        self.bn2 = nn.BatchNorm2d(32)
        
        # Global max pooling to reduce dimension before fully connected layers
        self.global_max_pool = nn.AdaptiveMaxPool2d((1, 1))
        
        # Fully connected layers for final prediction
        self.fc1 = nn.Linear(32 * 2, 128)  # Adjusted for concatenation
        self.fc2 = nn.Linear(128, 64)
        self.fc3 = nn.Linear(64, 1)
        self.dropout = nn.Dropout(0.5)
        
    def forward(self, antigen, antibody):
        # Apply 2D Convolutional layers with ReLU activations and BatchNorm on both inputs
        antigen = F.leaky_relu(self.bn1(self.conv1(antigen)))
        antigen = F.leaky_relu(self.bn2(self.conv2(antigen)))
        antigen = self.global_max_pool(antigen)

        antibody = F.leaky_relu(self.bn1(self.conv1(antibody)))
        antibody = F.leaky_relu(self.bn2(self.conv2(antibody)))
        antibody = self.global_max_pool(antibody)
        
        # Concatenate antigen and antibody feature maps
        x = torch.cat((antigen, antibody), dim=1)
        
        # Flatten the concatenated output
        x = x.view(x.size(0), -1)
        
        # Apply fully connected layers with dropout
        x = F.leaky_relu(self.fc1(x))
        x = self.dropout(x)
        x = F.leaky_relu(self.fc2(x))
        x = self.fc3(x)
        
        return x

In [36]:
class LitAffinityModel(pl.LightningModule):
    def __init__(self, train_loader, val_loader, test_loader, learning_rate=1e-3):
        super(LitAffinityModel, self).__init__()
        
        # Initialize the model
        embedding_dim = train_loader.dataset[0][0].size(-1)
        sequence_length = train_loader.dataset[0][0].size(-2)
        self.model = AffinityPredictor(embedding_dim=embedding_dim, sequence_length=sequence_length)
        self.learning_rate = learning_rate
        
        # Store data loaders
        self.train_loader = train_loader
        self.val_loader = val_loader
        self.test_loader = test_loader
        
        # Metrics
        self.train_mse = MeanSquaredError()
        self.val_mse = MeanSquaredError()
        self.test_mse = MeanSquaredError()

        # Store predictions and targets for plotting
        self.test_predictions = []
        self.test_targets = []
        
    def forward(self, antigen, antibody):
        return self.model(antigen, antibody)
    
    def training_step(self, batch, batch_idx):
        antigen, antibody, label = batch
        prediction = self(antigen, antibody).squeeze()
        loss = F.mse_loss(prediction, label)
        self.train_mse.update(prediction, label)
        self.log("train_loss", loss, on_epoch=True, prog_bar=True)
        return loss
    
    def validation_step(self, batch, batch_idx):
        antigen, antibody, label = batch
        prediction = self(antigen, antibody).squeeze()
        loss = F.mse_loss(prediction, label)
        self.val_mse.update(prediction, label)
        self.log("val_loss", loss, on_epoch=True, prog_bar=True)
        return loss
    
    def test_step(self, batch, batch_idx):
        antigen, antibody, label = batch
        prediction = self(antigen, antibody).squeeze()
        loss = F.mse_loss(prediction, label)
        self.test_mse.update(prediction, label)
        
        # Store predictions and targets for later
        self.test_predictions.append(prediction.cpu())
        self.test_targets.append(label.cpu())
        
        self.log("test_loss", loss, on_epoch=True, prog_bar=True)
        return loss
    
    def on_test_epoch_end(self):
        # Concatenate all predictions and targets
        predictions = torch.cat(self.test_predictions, dim=0)
        targets = torch.cat(self.test_targets, dim=0)
        
        # Plotting results
        plt.figure(figsize=(8, 8))
        plt.scatter(targets, predictions, alpha=0.5)
        plt.plot([min(targets), max(targets)], [min(targets), max(targets)], 'r--')  # Identity line
        plt.xlabel("True Values")
        plt.ylabel("Predictions")
        plt.title("Test Predictions vs True Values")
        plt.show()

    def configure_optimizers(self):
        optimizer = torch.optim.AdamW(self.parameters(), lr=self.learning_rate)
        scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(optimizer, mode='min', factor=0.1, patience=10)
        return {"optimizer": optimizer, "lr_scheduler": scheduler, "monitor": "val_loss"}

    def train_dataloader(self):
        return self.train_loader

    def val_dataloader(self):
        return self.val_loader

    def test_dataloader(self):
        return self.test_loader

In [37]:
def has_tensor_cores():
    gpu_name = torch.cuda.get_device_name(0)
    print(f"GPU: {gpu_name}")
    capability = torch.cuda.get_device_capability(0)
    print(f"Compute Capability: {capability}")
    return capability[0] >= 7 and capability[1] >= 0

use_mixed_precision = False
if torch.cuda.is_available():
    if has_tensor_cores():
        print("This GPU supports Tensor Cores.")
        use_mixed_precision = True
    else:
        print("This GPU does not support Tensor Cores.")
else:
    print("No GPU found.")

precision = 16 if use_mixed_precision else 32
if use_mixed_precision:
    torch.set_float32_matmul_precision("medium")  # Uses Tensor Cores for GPU

GPU: NVIDIA RTX 2000 Ada Generation Laptop GPU
Compute Capability: (8, 9)
This GPU supports Tensor Cores.

In [39]:
from pytorch_lightning import Trainer

# Define callbacks
checkpoint = pl.callbacks.ModelCheckpoint(monitor='val_loss', save_top_k=1)
early_stopping = pl.callbacks.EarlyStopping(monitor='val_loss', patience=20, mode='min')
lr_monitor = pl.callbacks.LearningRateMonitor(logging_interval='epoch')
device_stats = pl.callbacks.DeviceStatsMonitor()
progress_bar = pl.callbacks.TQDMProgressBar(refresh_rate=20)

# Initialize Trainer with callbacks
trainer = Trainer(
    max_epochs=100,
    callbacks=[checkpoint, early_stopping, lr_monitor, device_stats, progress_bar],
    precision=precision
)

Using 16bit Automatic Mixed Precision (AMP)
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

In [40]:
model = LitAffinityModel(train_loader, val_loader, test_loader)

In [ ]:
trainer.fit(model)

LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name      | Type              | Params | Mode
--------------------------------------------------------
0 | model     | AffinityPredictor | 21.5 K | train
1 | train_mse | MeanSquaredError  | 0      | train
2 | val_mse   | MeanSquaredError  | 0      | train
3 | test_mse  | MeanSquaredError  | 0      | train
--------------------------------------------------------
21.5 K    Trainable params
0         Non-trainable params
21.5 K    Total params
0.086     Total estimated model params size (MB)
13        Modules in train mode
0         Modules in eval mode

Sanity Checking: |                                                                                | 0/? [00:00…

In [ ]:
# Testing and plotting results
trainer.test(model)